[package]
name = "rs-wrk"
version = "0.1.0"
authors = ["fanxiaokai <xiaokai.fan@bitmain.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.32", features = ["yaml"] }
crossbeam-channel = "0.3"
crossbeam-utils = "0.6"
ctrlc = "3.1"
hdrhistogram = "6.1"
reqwest = "0.9"
url = "1.7"
